SET FOREIGN_KEY_CHECKS=0;
DROP TABLE casting;
DROP TABLE `character`;
DROP TABLE company;
DROP TABLE country;
DROP TABLE episode;
DROP TABLE gender;
DROP TABLE `name`;
DROP TABLE person;
DROP TABLE production;
DROP TABLE productioncompany;
DROP TABLE role;
DROP TABLE season;
DROP TABLE serie;
DROP TABLE singleproduction;
DROP TABLE title;
DROP TABLE `type`;
SET FOREIGN_KEY_CHECKS=1;